# Generated by Django 3.2 on 2024-08-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='customer_email',
            new_name='Correo_Electronico',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='message',
            new_name='Mensaje',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='customer_name',
            new_name='Nombre',
        ),
    ]
